import { Inter } from "next/font/google";
import SessionProviderWrapper from './sessionproviderwrapper';
import "./globals.css";
import Header from './header.js'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper session= {session}>
          <Header />
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}